name: Cross-Platform C++ Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y g++ make

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install gcc make

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: Compile
        run: |
          g++ -o bars-patcher main.cpp

      - name: Upload Executable (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: bars-patcher-linux
          path: bars-patcher

      - name: Upload Executable (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: bars-patcher-macos
          path: bars-patcher

      - name: Upload Executable (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: bars-patcher-windows
          path: bars-patcher.exe
