name: Cross-Platform C++ Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y g++

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install gcc

      - name: Compile (Windows)
        if: runner.os == 'Windows'
        run: g++ -static -o bars-patcher-windows.exe main.cpp

      - name: Compile (Linux)
        if: runner.os == 'Linux'
        run: g++ -static -o bars-patcher-linux main.cpp

      - name: Compile (macOS)
        if: runner.os == 'macOS'
        run: clang++ -o bars-patcher-macos main.cpp -static-libstdc++

      - name: Upload Executable (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: bars-patcher-windows
          path: bars-patcher-windows.exe

      - name: Upload Executable (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: bars-patcher-linux
          path: bars-patcher-linux

      - name: Upload Executable (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: bars-patcher-macos
          path: bars-patcher-macos
